# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c02197daf7fcb9c0f70441a020e7672421b5d5534fd5819bc754679d85b85ba1764bd878db5849102566853517519a11d69c37b57da8ffb899619d14477d38e

test:
  secret_key_base: 56dc88298b064ba7f40bc4400ce89a1f76a13ef4fb95b2a8b68589cd2e7552a4a9cc3f55bb215530d0392dba05d5af4e9af9bf35adbb7795a8975336ffb8056c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
